name: Update & deploy application code on remote server
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  deploy:
    if: github.event.pull_request.merged == true
    name: Update & deploy application code on remote server
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect to remote server
        env:
          PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
          HOSTNAME: ${{secrets.HOSTNAME}}
          USER_NAME: ${{secrets.USER_NAME}}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          echo "Connected to the server"
          echo "Script execution started"

          echo "Stopping container"
          sudo docker stop backend-app

          echo "Removing containers"
          sudo docker container prune

          echo "Removing images"
          sudo docker rmi $(sudo docker images -a -q)

          echo "Setting up repository"
          echo "Removing old project"

          cd /home/ubuntu/services
          sudo rm -r -f ./backend

          sudo mkdir backend
          cd backend
          echo "Initialization git repository"
          sudo git config --global --add safe.directory /home/ubuntu/services/backend
          sudo git init
          echo "Adding remote repository"
          sudo git remote add origin https://$GITHUB_TOKEN@github.com/EdTech-Project/backend.git
          sudo git pull origin dev
          if [ $? -eq 0 ]; then
            echo "GIT pull success"
          else
            echo "GIT pull failure"
            exit 1;
          fi

          echo "Creating config .env file"

          sudo cp /etc/environment /home/ubuntu/services/backend/.env

          echo "Building images"

          sudo docker compose build
          sudo docker compose up -d
          sudo docker ps
          '
